
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "lynx/annotation/reflectionclassparser.zep.h"
#include "lynx/annotation/regexdocparser.zep.h"
#include "lynx/dbal/connection.zep.h"
#include "lynx/dbal/driver/connection.zep.h"
#include "lynx/dbal/driver/mysql.zep.h"
#include "lynx/dbal/driver/pdo/statement.zep.h"
#include "lynx/dbal/driver/pdoconnection.zep.h"
#include "lynx/dbal/driver/pdo.zep.h"
#include "lynx/dbal/driver/pgsql.zep.h"
#include "lynx/dbal/events.zep.h"
#include "lynx/dbal/platform/mysql.zep.h"
#include "lynx/dbal/platform/pgsql.zep.h"
#include "lynx/dbal/rawvalue.zep.h"
#include "lynx/orm/configuration.zep.h"
#include "lynx/orm/entitymanager.zep.h"
#include "lynx/orm/entityrepository.zep.h"
#include "lynx/orm/exception.zep.h"
#include "lynx/orm/modelmetadata.zep.h"
#include "lynx/orm/modelmetadata/column.zep.h"
#include "lynx/orm/modelmetadata/property.zep.h"
#include "lynx/orm/modelsmanager.zep.h"
#include "lynx/orm/query.zep.h"
#include "lynx/orm/querybuilder.zep.h"
#include "lynx/orm/querybuilder/expression/join.zep.h"
#include "lynx/orm/querybuilder/expression/where.zep.h"
#include "lynx/orm/queryidentitymap.zep.h"
#include "lynx/orm/sqlbuilder.zep.h"
#include "lynx/orm/unitofwork.zep.h"
#include "lynx/stdlib/collections/arraycollection.zep.h"
#include "lynx/stdlib/collections/collection.zep.h"
#include "lynx/stdlib/events/event.zep.h"
#include "lynx/stdlib/events/eventsmanager.zep.h"
#include "lynx/stdlib/events/manager.zep.h"
#include "lynx/stdlib/hydrator/classmethods.zep.h"
#include "lynx/stdlib/hydrator/classproperties.zep.h"
#include "lynx/stdlib/hydrator/entity.zep.h"
#include "lynx/stdlib/hydrator/hydrator.zep.h"

#endif