phalcon.lo: /home/zaets28rus/projects/phalcon-orm/ext/phalcon.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/phalcon.c -o phalcon.lo 
kernel/main.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/require.c -o kernel/require.lo 
kernel/alternative/fcall.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/alternative/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/alternative/fcall.c -o kernel/alternative/fcall.lo 
kernel/file.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/zaets28rus/projects/phalcon-orm/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/kernel/variables.c -o kernel/variables.lo 
phalcon/orm/entitymanager.lo: /home/zaets28rus/projects/phalcon-orm/ext/phalcon/orm/entitymanager.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/zaets28rus/projects/phalcon-orm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/zaets28rus/projects/phalcon-orm/ext/phalcon/orm/entitymanager.c -o phalcon/orm/entitymanager.lo 
$(phplibdir)/phalcon.la: ./phalcon.la
	$(LIBTOOL) --mode=install cp ./phalcon.la $(phplibdir)

./phalcon.la: $(shared_objects_phalcon) $(PHALCON_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_phalcon) $(PHALCON_SHARED_LIBADD)

